# ------------------------------------
#   欢迎您使用阿里云函数计算 FC 组件进行项目开发
#   组件仓库地址/帮助文档：https://github.com/devsapp/fc
#   Yaml参考文档：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/yaml.md
#   快速入门：
#      快速创建应用：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/quick_start_application.md
#      快速使用命令：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/quick_start_function.md
# ------------------------------------

edition: 1.0.0
name: word2pdf
access: '{{access}}'

services:
  word2pdf:
    component: fc
    actions:
      pre-deploy:
        - run: s build --use-docker --dockerfile ./code/Dockerfile
          path: ./
    props:
      region: cn-hangzhou
      service:
        name: fc-liboffice
        description: 'make a word change to pdf'
        internetAccess: true
        #logConfig: auto
      function:
        name: word2pdf
        runtime: custom-container
        codeUri: ./code
        memorySize: 3072
        timeout: 900
        caPort: 9000
        customContainerConfig:
          image: registry-vpc.cn-hangzhou.aliyuncs.com/fc-demo/fc-liboffice:v0.4
        environmentVariables:
          TZ: Asia/Shanghai
          OSS_BUCKET: <your bucket>
          OSS_AK_ID: <your ak id>
          OSS_AK_SECRET: <your ak secret>